package com.ssafy.DDGo.users.domain;

import com.ssafy.DDGo.global.exception.CustomException;
import com.ssafy.DDGo.global.exception.ErrorCode;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Builds readable Korean auto-generated nicknames from curated adjective+noun pairs.
 */
public class AutoGeneratedNicknamePolicy {

    private static final int MAX_NICKNAME_LENGTH = 20;

    private static final List<String> ADJECTIVES = List.of(
            "맑은", "고운", "따뜻한", "포근한", "잔잔한", "반가운", "느긋한", "다정한",
            "성실한", "든든한", "기분좋은", "반듯한", "빛나는", "산뜻한", "부드러운", "단단한",
            "쾌적한", "수수한", "싱그러운", "평온한", "행복한", "정다운", "차분한", "부지런한",
            "사뿐한", "영롱한", "명랑한", "온화한", "풍성한", "정직한", "튼튼한", "상냥한"
    );

    private static final List<String> NOUNS = List.of(
            "하늘", "바람", "구름", "햇살", "달빛", "별빛", "노을", "새벽",
            "산책", "호수", "물결", "파도", "나무", "숲길", "이슬", "꽃잎",
            "나비", "새싹", "열매", "고래", "갈매기", "바다", "언덕", "들판",
            "모래", "잔디", "고양이", "강물", "시냇물", "솔바람", "산들", "여울",
            "반딧불", "풀잎", "오솔길", "산호", "초원", "은하", "소나무", "고운별"
    );

    private final List<String> candidates;

    public AutoGeneratedNicknamePolicy() {
        List<String> generatedCandidates = new ArrayList<>();
        for (String adjective : ADJECTIVES) {
            for (String noun : NOUNS) {
                String candidate = adjective + noun;
                if (candidate.length() <= MAX_NICKNAME_LENGTH) {
                    generatedCandidates.add(candidate);
                }
            }
        }

        if (generatedCandidates.isEmpty()) {
            throw new CustomException(ErrorCode.INTERNAL_SERVER_ERROR, "자동 닉네임 후보 생성에 실패했습니다.");
        }

        this.candidates = Collections.unmodifiableList(generatedCandidates);
    }

    public String randomCandidate(Random random) {
        return candidates.get(random.nextInt(candidates.size()));
    }

    public String candidateAt(int index) {
        int normalizedIndex = Math.floorMod(index, candidates.size());
        return candidates.get(normalizedIndex);
    }

    public int size() {
        return candidates.size();
    }
}
